server:
  application.name: demo
  port: 9898
management:
  server.port: 8082
  # now monitoring can be done from management port instead of server port i.e. http://localhost:8081/actuator/monitoring
  endpoints:
    web.exposure.include: info,health,monitoring 
    shutdown.enabled: true

logging.level.root: INFO
## Default connection pool for spring boot starter JPA - HikariCP

spring:
  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      # remote access
      web-allow-others: false
  jpa:
    # As we are loading sql from file switch this off
    hibernate.ddl-auto: none 
    show-sql: true
    properties.hibernate:
      format_sql: true
      generate_statistics: false
  datasource:
    # platform helps to pick up the right script to initialize viz. initialization-mode: [embedded] | never | always
    platform: h2
    # earlier it was url with hikari its jdbc-url
    jdbc-url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1;USER=sa;PASSWORD=sa
  second-datasource:
    platform: mysql
    initialization-mode: always
    jdbc-url: jdbc:mysql://test-user:test-password@localhost:3306/testdb?createDatabaseIfNotExist=true
#    schema: file:mysql-schema.sql
#    data: classpath:mysql-data.sql
  data.mongodb.uri: mongodb://test-user:test-password@localhost:27017/testdb
  devtools:
    remote:
      # Enables server to allow debugging - risky
      secret: mysecret
      # TODO org.springframework.boot.devtools.RemoteSpringApplication http://localhost:9898
      debug.local-port: 8899
    
javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true
  # Data source names to exclude from monitoring (optional, comma-separated)
  #excluded-datasources: secretSource,topSecretSource
  # Enable monitoring of Spring services and controllers using @MonitoredWithSpring (optional, default: true)
  spring-monitoring-enabled: true
  # scheduled-monitoring-enabled -- for @Scheduled
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  # Endpoint /monitoring reports on the management http port instead of the application http port
  management-endpoint-monitoring-enabled: true
  init-parameters:
    # log http requests:
    log: true
    # to exclude images, css, fonts and js urls from the monitoring:
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # to aggregate digits in http requests:
    #http-transform-pattern: \d+
    # to add basic auth:
    #authorized-users: admin:pwd
    # to change the default storage directory:
    #storage-directory: /tmp/javamelody
    # to change the default "/monitoring" path:
    #monitoring-path: /admin/performance