-- CREATE DATABASE IF NOT EXISTS
CREATE SCHEMA IF NOT EXISTS myDb;

DROP TABLE IF EXISTS users;
 
CREATE TABLE users (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  firstname VARCHAR(25) NOT NULL,
  lastname VARCHAR(25) NOT NULL,
  age INT DEFAULT NULL
);

DROP TABLE IF EXISTS vehicles;
 
CREATE TABLE vehicles (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  type VARCHAR(25) NOT NULL,
  model_code VARCHAR(25) NOT NULL,
  brand_name VARCHAR(25),
  launch_date DATE
);
