-- CREATE DATABASE IF NOT EXISTS
CREATE SCHEMA IF NOT EXISTS myDb;

DROP TABLE IF EXISTS users;
 
CREATE TABLE users (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  firstname VARCHAR(25) NOT NULL,
  lastname VARCHAR(25) NOT NULL,
  age INT DEFAULT NULL
);
