-- CREATE DATABASE IF NOT EXISTS
CREATE SCHEMA IF NOT EXISTS myDb;

DROP TABLE IF EXISTS users;
 
CREATE TABLE users (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(25) NOT NULL,
  last_name VARCHAR(25) NOT NULL,
  age INT DEFAULT NULL
);
 
DROP TABLE IF EXISTS products;
 
CREATE TABLE products (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(25) NOT NULL,
  price DOUBLE DEFAULT NULL
);
